//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial struct Card : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Game.server.CardSuit suitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Game.server.CardValues valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Game.server.CardSuit suit {
            get {
                return this.suitField;
            }
            set {
                if ((this.suitField.Equals(value) != true)) {
                    this.suitField = value;
                    this.RaisePropertyChanged("suit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Game.server.CardValues value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSuit", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public enum CardSuit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HEARTS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIAMONDS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLUBS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPADES = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardValues", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public enum CardValues : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIX = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEVEN = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EIGHT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NINE = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TEN = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JACK = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUEEN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KING = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACE = 14,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Server", ConfigurationName="server.IService", CallbackContract=typeof(Game.server.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Server/IService/joinGame", ReplyAction="Server/IService/joinGameResponse")]
        int joinGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/play")]
        void play(int playerID, Game.server.Card card);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/startGame")]
        void startGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/startTurn")]
        void startTurn(Game.server.Card[] tableCards, Game.server.Card[] playerCards);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/endGame")]
        void endGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/drawCards")]
        void drawCards(Game.server.Card[] playerCards);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/victory")]
        void victory();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Server/IService/loss")]
        void loss();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Game.server.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<Game.server.IService>, Game.server.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int joinGame() {
            return base.Channel.joinGame();
        }
        
        public void play(int playerID, Game.server.Card card) {
            base.Channel.play(playerID, card);
        }
    }
}
